create parser class

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -84,7 +84,7 @@ jobs:
         sudo apt-get install -y clang-format
 
     - name: Check code formatting
-      run: find src \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -Werror --style=file -n {} + || (echo "Clang-format failed!" && exit 1)
+      run: find include src \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -Werror --style=file -n {} + || (echo "Clang-format failed!" && exit 1)
   
   # =========================================================
   # Clang Tidy Job
